spring:
  profiles:
    active: dev
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://114.215.41.113:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: root
     password: Zhangliang@520

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
